stream:
  topic: transaction-service-input
  checkpoint-location: s3a://data-ice-lake-05/master/data/source/spark-streaming-checkpoints
  output-path: s3a://data-ice-lake-05/master/data/source/streaming-query
  app-name: app
  query-name: query
  processing-time: 30 seconds
