apps:
  transaction-service-stream-collector:
    prod: &config
      topic: transaction-service-input
      checkpoint-location: s3a://data-ice-lake-05/prod/source/spark-streaming-checkpoints/stream
      output-path: &stream-prod-output-path s3a://data-ice-lake-05/prod/source/streaming-query
      app-name: app
      query-name: query
      trigger:
        processing-time: 2 minutes # 30 seconds
        offsets-per-trigger: 50000 #10000
    dev:
      <<: *config
      checkpoint-location: s3a://data-ice-lake-05/dev/source/spark-streaming-checkpoints/stream
      output-path: &stream-dev-output-path s3a://data-ice-lake-05/dev/source/streaming-query
      app-name: app-dev
      query-name: query-dev
    test:
      <<: *config
      checkpoint-location: s3a://data-ice-lake-05/test/source/spark-streaming-checkpoints/stream
      output-path: &stream-test-output-path s3a://data-ice-lake-05/test/source/streaming-query
      app-name: app-test
      query-name: query-test

  static:
    prod: &config
      input-path: *stream-prod-output-path
      app-name: app
    dev:
      <<: *static-config
      input-path: *stream-dev-output-path
      app-name: app-dev
    test:
      <<: *static-config
      input-path: *stream-test-output-path
      app-name: app-test
