app:
  name: transaction-service-clean-collector-app
  prod:
    input-path: s3a://data-ice-lake-05/prod/source/transaction-service
    output-path: s3a://data-ice-lake-05/prod/clean/transaction-service
    app-name: transaction-service-clean-collector
  dev:
    input-path: s3a://data-ice-lake-05/test/source/transaction-service
    output-path: s3a://data-ice-lake-05/dev/clean/transaction-service
    app-name: transaction-service-clean-collector-dev
  test:
    input-path: s3a://data-ice-lake-05/test/source/transaction-service
    output-path: s3a://data-ice-lake-05/test/clean/transaction-service
    app-name: transaction-service-clean-collector-test
