app:
  name: transaction-service-stream-collector
  prod: &config
    topic: transaction-service-input
    checkpoint-location: s3a://data-ice-lake-05/prod/source/spark-streaming-checkpoints/stream
    output-path: s3a://data-ice-lake-05/prod/source/streaming-query
    app-name: app
    query-name: query
    trigger:
      processing-time: 30 seconds
      offsets-per-trigger: 10000
  dev:
    <<: *config
    checkpoint-location: s3a://data-ice-lake-05/dev/source/spark-streaming-checkpoints/stream
    output-path: s3a://data-ice-lake-05/dev/source/streaming-query
    app-name: app-dev
    query-name: query-dev
  test:
    <<: *config
    checkpoint-location: s3a://data-ice-lake-05/test/source/spark-streaming-checkpoints/stream
    output-path: s3a://data-ice-lake-05/test/source/streaming-query
    app-name: app-test
    query-name: query-test
