app:
  name: transaction-service-stream-collector
  prod: &config
    topic: transaction-service-input
    output-path: s3a://data-ice-lake-05/prod/source/transaction-service
    app-name: transaction-service-stream-collector-app
    query-name: transaction-service-stream-collector-query
    checkpoint-location: s3a://data-ice-lake-05/prod/source/spark-streaming-checkpoints/transaction-service
    trigger:
      processing-time: 60 seconds
      offsets-per-trigger: 10000
    deduplicate:
      cols-subset: ["object_id", "object_type", "sent_dttm"]
      delay-threshold: 60 seconds
  dev:
    <<: *config
    output-path: s3a://data-ice-lake-05/dev/source/transaction-service
    app-name: transaction-service-stream-collector-dev
    query-name: transaction-service-stream-collector-dev-query
    checkpoint-location: s3a://data-ice-lake-05/dev/source/spark-streaming-checkpoints/transaction-service
  test:
    <<: *config
    output-path: s3a://data-ice-lake-05/test/source/transaction-service
    app-name: transaction-service-stream-collector-test
    query-name: transaction-service-stream-collector-test-query
    checkpoint-location: s3a://data-ice-lake-05/test/source/spark-streaming-checkpoints/transaction-service
